---
- name: Play book for installing webserver in all the nodes 
  hosts: all
  become: true
  gather_facts: yes
  vars:
   - port: 8081
  tasks:
   - name: installing httpd in redhat os
     yum:
      name: httpd
      state: present
     when: ansible_os_family == "RedHat"
     notify: staring apache

   - name: installing httpd in Debian os
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Debian"
     notify: staring apache2

   - name: copying index page in to host machines
     copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
   - name: changing default port 
     lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}   
     when: ansible_os_family == "RedHat"
   
   - name: changing default port
     lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
     when: ansible_os_family == "Debian"
  handlers:
   - name: staring apache
     service: 
      name: httpd
      state: started
   - name: staring apache2 
     service:
      name: apache2
      state: started

