---
- name: Playbook for copy 
  hosts: all
  become: true
  tasks:
   - name: copy index file to hosts
     copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: ansadmin


