---
- name: play-book for installing httpd 
  hosts: webservers
  become: true
  tasks:
   - name: installing httpd in webservers
     yum:
      name: httpd
      state: present
     notify: starting httpd

  handlers:
   - name: starting httpd 
     service:
      name: httpd
      state: started

