---
- name: installing tomcat
  hosts: all
  become: false 
  tasks:
    - name: install java in RedHat
      yum:
        name: java
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: install java in ubuntu
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"
    
    - name: downlaoding tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.37/bin/apache-tomcat-9.0.37.tar.gz
        dest: /opt
      ignore_errors: yes
    
    - name: untar apache packages
      unarchive:
        src: /opt/apache-tomcat-9.0.37.tar.gz
        dest: /opt
        remote_src: yes
      ignore_errors: yes

    - name: add execution permition to startup.sh script
      file:
        path: /opt/apache-tomcat-8.5.57/bin/startup.sh
        mode: 0700
        owner: ansadmin
      ignore_errors: yes
    
    - name: starting tomcat service
      shell: nohup startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.57/bin



