---
- name: play-book for installing httpd 
  hosts: webservers
  become: true
  tasks:
   - name: stopping  httpd in webservers
     service:
      name: httpd
      state: stopped
   - name: removing httpd 
     yum:
      name: httpd
      state: absent

