---
- name: Play book for unstalling webserver in all the nodes
  hosts: all
  become: true
  gather_facts: yes
  tasks:
   - name: stopping httpd
     service:
      name: httpd
      state: stopped
     when: ansible_os_family == "RedHat"

   - name: unstalling httpd in redhat os
     yum:
      name: httpd
      state: absent
     when: ansible_os_family == "RedHat"
  
   - name: stopping in Debian
     service:
      name: apache2
      state: stopped
     when: ansible_os_family == "Debian"
   - name: removing n Debian os
     apt:
      name: apache2
      state: absent
     when: ansible_os_family == "Debian"
  
